### ISSUE TITLE
Create_schema check for seeing if timestamp, component_id, and job_id are present is broken.

### ISSUE THREAD

**Issue by bschwal** [ovis-hpc/ldms#1099]
I added a sampler and sos store for lustre_ods which does not have the job_id field because it is run on backend lustre servers. When I started the sampler a sos schema was made for lustre_ost with job_id as a field and it used as an index. On the first instance of the data trying to be stored the daemon dies because no job_id is present in the metric set (or at least not where it thinks it is). 

I think there needs to be some checking in create_schema to see if the data is exists before executing a sos_schema_attr_add. Perhaps two code paths, one for if job_id is present and one if it is not (since timestamp and component_id should be in every schema).

**Comment by tom95858** [comment]
Hi Ben,

We should look at addressing all of this with decomposition which doesn't have the built in assumptions like the one you just alluded to.

**Comment by tom95858** [comment]
@bschwal did you check this out with decomposition?

**Comment by tom95858** [comment]
@bschwal, i think this is still a bug, I'm just suggesting that you try decomposition to get going. There are man page(s) on decomposition and I can provide examples as well.

**Comment by tom95858** [comment]
@bschwal, please reopen if necessary.

**Comment by bschwal** [comment]
[ldms](https://github.com/ovis-hpc/ldms/tree/b4.4)/[ldms](https://github.com/ovis-hpc/ldms/tree/b4.4/ldms)/[src](https://github.com/ovis-hpc/ldms/tree/b4.4/ldms/src)/[store](https://github.com/ovis-hpc/ldms/tree/b4.4/ldms/src/store)

@tom95858  it appears /store_sos.c checks if job_id/timestamp/component_id exist and if not goes to err_1. I couldn't track down what err_1 means in this context so if that's not correct please open. If it just raises a flag that's fine, but I wouldn't want it to stop the create_schema.

**Comment by tom95858** [comment]
@bschwal, the issue is that the 'default' commit() assumes that the metric set includes those metrics. The reason is that it has 6 default indices that require these values to be created. By default, you don't specify indices, they are assumed by the store (in this case sos).

Subsequent to the initial implementation we added decomposition and a new call, commit_rows(), to the implementation. This allowed the storage policy to specify the indices explicitly in a configuration file. That's why I pointed you at that approach. Although you suggested otherwise, it doesn't seem correct to create an index for which the key contains random values, i.e. a metric set that doesn't have a job-id. We could certainly do that, but I contend it would add to more confusion for the user that might then expect that they could reasonably query on job-id when it's value is actually always zero.

I am going to close this issue, please move it to a discussion topic to further explore what we want to do here.
