### ISSUE TITLE
Installing Python Support For LDMS

### ISSUE THREAD

**Issue by Snell1224** [ovis-hpc/ldms#1341]
Not really an issue but more of a question -- has there been a new change that default disables python for ldms? 

I noticed that when configuring and installing the current version of LDMS with:

``
 ../configure --prefix=/home/user/ovis/build/ --enable-etc && make && make install
``

The site-packages for python-3.6 is not built (i.e. no ``../ovis/build/lib/python3.6/`` directory). I have never had this issue before because, for as long as I have used LDMS, python support was always default enabled.

Now if I build the code with ``--enable-ldms-python`` then this fixes the problem and the python site-packages are installed (``--enable-python`` does not fix this). 

I couldn't find anything in the documentation or ``configure.ac`` that indicates that this is default disabled. I am wondering if this was an intentional change so I can let my team know that any LDMS build/test scripts will need to be updated to include this flag.

**Comment by nichamon** [comment]
I was about to create an issue, but I saw this first. I ran into the same situation. 

I also installed libpython3-dev. LDMS was successfully built. However, `ldmsd_controller` isn't present in `$PREFIX/bin` and as @Snell1224 reported, the python packages are not installed in the $PREFIX/lib.

OS: Linux Mint 21.3, which is based on Ubuntu 22.04.
autoconf (GNU Autoconf): 2.71
libtoolize (GNU libtool) 2.4.6

@morrone Any suggestions on this? Here is the [config.log](https://github.com/ovis-hpc/ovis/files/14142664/config-anon.log) from my build, which I anonymized the hostname and my home name.

**Comment by nichamon** [comment]
@tom95858 @narategithub I forgot to tag you guys in my previous comment.

**Comment by nichamon** [comment]
With further inspection, I think I had the same symptom as @Snell1224 because I forgot to install `cython3`. I just reinstalled my machine. After I installed `cython3` and `libpython3-dev`, `ldmsd_controller` and the ldms python modules got built without specifying `--enable-ldms-python`.

@Snell1224 Were `cython3` and `libpython3-dev` installed when you built `ldms` without `--enable-ldms-python`? Did you need to install any libraries to make `--enable-ldms-python` work?

**Comment by morrone** [comment]
I took a look at configure.ac to see how --enable-python and --enable-ldms-python are handled.

First of all, --enable-ldms-python is deprecated, and should not be used.

Second, I can see no difference between specifying --enable-python and --enable-ldms-python. Both would trigger the exact same tests to be run, and either enable to disable building the "python" SUBDIR in the ovis ldms source tree. So I'm a little skeptical of the claim that --enable-ldms-python behaved differently than --enable-python. I would think it more likely that there was a typo or or something along the way.

The main difference between specifying --enable-python/--enable-ldms-python and just leaving those options out all together, is that when neither are specified configure will only warn about python and/or cython being missing. _With_ one of those options specified, configure will throw an error if python or cython is missing.

And finally, it is more correct to say that configure's default behavior for python is to conditionally test if python/cython are available, enabling the build of python components when the requirements are found (it has been so since at least 2020).  "--enable-python" essentially just turns the lack of python/cython into an error at configure time.

@Snell1224 , if that isn't the behavior that you are seeing, then we'll probably need config.log files to get to the bottom of the problem.

**Comment by Snell1224** [comment]
Yes, there was a mistake when building the LDMS code with ``--enable-python``. I did not run the ``make install`` which is why it didn't appear in the /lib directory. Now both ``python`` flags are working (will not be using ``--enable-ldms-python`` anymore).

Ah that makes sense thank you for the information! I rebuilt the LDMS code yesterday without the python flags and the ``/lib/python3.6`` was installed. I'm starting to think that the reason this wasn't installed before is because LDMS didn't detect python/cython (maybe one of them were not set in my $PATH). 

Either way, the python components are now installing successfully! I'll go ahead and close this issue. Thank you again @nichamon and @morrone for your help!

**Comment by baallan** [comment]
@jennfshr reports related experiences.

**Comment by morrone** [comment]
This ticket is closed, so it will not show up in the list of tickets that need attention. I would recommend a new ticket for a new problem, even if it seems related. You can certainly mention this closed ticket in that new ticket.

**Comment by tom95858** [comment]
Can someone please articulate exactly that the problem is?

**Comment by tom95858** [comment]
Hi everyone, can we please get to closure on this. What specific changes do we need to make to configure.ac to "fix" this. Or is this a documentation issue that needs to go in the top level readme?

**Comment by tom95858** [comment]
Please reopen if necessary
