### ISSUE TITLE
Row cache in Operator Decomposition is not cleaned up after corresponding sets have been deleted

### ISSUE THREAD

**Issue by nichamon** [ovis-hpc/ldms#1483]

**Comment by nichamon** [comment]
Resolved by #1525

**Comment by morrone** [comment]
Correct me if I am wrong, but it looks like #1525 clears the cache after time period is exceeded rather than when the metric set is deleted. Am I understanding that right? If so, it looks like this is certainly an improvement, but it isn't necessarily the same as removing the row cache after the set is deleted.

For instance, the decomposition code only sees row data from metric sets when the sets are updated, right? So for samplers that only update metric sets when there has been change (there are lustre ones that work this way), there may be gaps that result in the cache being cleared while the metric set is still live.

It would be great to have an explanation of what is going on with the three buckets too. I think that is too complicated to leave undocumented in the code.

**Comment by morrone** [comment]
There was no included documentation about the new "timeout" decomposition option either.

**Comment by emdonat** [comment]
@morrone Will the implementation with a timeout as implemented in #1525 preclude a 4.4.5 release?  It seems that we are ok moving forward now and improving implementation over upcoming releases?

**Comment by morrone** [comment]
> @morrone Will the implementation with a timeout as implemented in #1525 preclude a 4.4.5 release? It seems that we are ok moving forward now and improving implementation over upcoming releases?

I think the timeout is OK for 4.4.5. I'll close this one again and open a separate ticket to remember the improvements that could be done in the future.
